title: Harry Richards
logo: /assets/img/headshot_CIRCLE.JPG
LinkedIn: https://www.linkedin.com/in/hrichards098/
github: https://github.com/hrichards-data
CV: /assets/HARRY_RICHARDS_CV.pdf

show_downloads: false
theme: jekyll-theme-minimal
